services:
  db:
    image: postgres:18.4
    container_name: shop_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: shop_minio
    restart: unless-stopped
    ports:
      - "9000:9000" # پورت API
      - "9001:9001" # پورت پنل مدیریت (کنسول)
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio-setup:
    image: minio/mc:latest
    container_name: shop_minio_setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/shop-media --ignore-existing;
      /usr/bin/mc anonymous set download myminio/shop-media;
      exit 0;
      "

  backend:
    build:
      context: ./backend
    container_name: shop_backend
    restart: unless-stopped
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/api/health/')\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - FRONTEND_BASE_URL=http://localhost:3000

  frontend:
    build:
      context: ./frontend
    container_name: shop_frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"

    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next

    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"

    command: npm run dev -- --hostname 0.0.0.0

    depends_on:
      backend:
        condition: service_healthy

  storybook:
    build:
      context: ./frontend
    command: npm run storybook -- --host 0.0.0.0
    ports:
      - "6006:6006"
    volumes:
      - ./frontend:/app
      - storybook_node_modules:/app/node_modules



volumes:
  postgres_data:
  minio_data:
  frontend_node_modules:
  frontend_next:
  storybook_node_modules:
