# Generated by Django 5.2.16 on 2026-07-15 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان کتاب')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('author', models.CharField(max_length=255, verbose_name='نویسنده / پدیدآورنده')),
                ('translator', models.CharField(blank=True, max_length=255, null=True, verbose_name='مترجم')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='شابک (ISBN)')),
                ('number_of_pages', models.PositiveIntegerField(verbose_name='تعداد صفحات')),
                ('publish_year', models.PositiveIntegerField(verbose_name='سال انتشار (شمسی)')),
                ('cover_type', models.CharField(choices=[('hardback', 'گالینگور (جلد سخت)'), ('paperback', 'شومیز (جلد نرم)'), ('pocket', 'جیبی')], default='paperback', max_length=20, verbose_name='نوع جلد')),
                ('description', models.TextField(blank=True, verbose_name='خلاصه/توضیحات کتاب')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت (تومان)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت انتشار در سایت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books/', verbose_name='تصویر جلد')),
                ('is_main', models.BooleanField(default=False, verbose_name='تصویر اصلی جلد')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.book', verbose_name='کتاب')),
            ],
            options={
                'verbose_name': 'تصویر کتاب',
                'verbose_name_plural': 'تصاویر کتاب\u200cها',
            },
        ),
    ]
